void Spaceshipv(float4 position : POSITION,
                float2 tcoord0 : TEXCOORD0,
                   
				out float4 oPosition : POSITION,
                out float2 oTCoord0 : TEXCOORD0,
                   
                uniform float4x4 modelViewProj)          
{
	/* Transform position from object space to clip space */
	oPosition = mul(modelViewProj, position);
	oTCoord0 = tcoord0;
}

void Spaceshipf(float2 tcoord0 : TEXCOORD0,

                out float4 oColor : COLOR,
                   
                uniform sampler2D diffTex,
                uniform sampler2D specTex)                 
                                                            
{
	float4 diffColor = tex2D(diffTex, tcoord0);
	float4 glowColor = tex2D(specTex, tcoord0);
	oColor = diffColor + glowColor;
}